# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=2048']
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # python checks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # js/ts checks
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npm --prefix app/ run check:eslint
        language: node
        files: app/.*\.[tj]sx?$
        pass_filenames: false
  - repo: local
    hooks:
      - id: tsc
        name: tsc
        entry: npm --prefix app/ run check:tsc
        language: node
        files: app/.*
        pass_filenames: false
